# https://taskfile.dev

version: '3'

vars:
  AUTORECONF:
    sh: |
      cygpath --windows /usr/bin/autoreconf

env:
  PKG_INSTALLDIR: '{{.TASKFILE_DIR}}'

tasks:
  default:
    deps: [autoreconf]
    cmds:
      - cmd: |
          uv run ./make_lite.py || true
      - cmd: |
          sh "{{joinPath .TASKFILE_DIR "configure"}}" \
            --enable-werror
      - cmd: |
          make
      - cmd: |
          make check
      - cmd: |
          cmake \
              -B CMakeBuild \
              -S . \
              -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_SHARED_LIBS=ON \
              -DBUILD_REGTEST=OFF \
              -DBUILD_EXAMPLES=OFF
      - cmd: |
          cmake --build CMakeBuild
      
  autoreconf:
    desc: Run autoreconf
    vars:
      AUTORECONF:
        sh: |
          cygpath --windows /usr/bin/autoreconf
      AUTOUPDATE:
        sh: |
          cygpath --windows /usr/bin/autoupdate
    cmds:
      - cmd: |
          sh "{{toSlash .AUTOUPDATE}}" -fv
          sh "{{toSlash .AUTORECONF}}" -fvi

  deps:
    cmds:
      - cmd: |
          pacman -Syu
      - cmd: |
          pacman -S --needed --noconfirm \
            pkg-config autoconf2.72 automake1.17 libtool make \
            ${MINGW_PACKAGE_PREFIX}-gcc \
            ${MINGW_PACKAGE_PREFIX}-autotools \
            ${MINGW_PACKAGE_PREFIX}-libtool
