# https://taskfile.dev

version: '3'

vars:
  AUTOUPDATE:
    sh: |
      if command -v cygpath > /dev/null; then
        cygpath --windows /usr/bin/autoupdate
      else
        echo "/usr/bin/autoupdate"
      fi
  AUTORECONF:
    sh: |
      if command -v cygpath > /dev/null; then
        cygpath --windows /usr/bin/autoreconf
      else
        echo "/usr/bin/autoreconf"
      fi

env:
  PKG_INSTALLDIR: '{{.TASKFILE_DIR}}'

tasks:
  default:
    deps: [autoreconf]
    cmds:
      - cmd: |
          if ! uv venv --allow-existing; then
            rm -rf .venv
            uv venv
          fi
      - cmd: |
          uv sync --locked
      - cmd: |
          uv run --no-sync ./make_lite.py || true
      - cmd: |
          sh "{{joinPath .TASKFILE_DIR "configure"}}" \
            --enable-werror
      - cmd: |
          make
      - cmd: |
          make check
      - cmd: |
          uv run --no-sync cmake \
              -B CMakeBuild \
              -S . \
              -DCMAKE_BUILD_TYPE=Release \
              -DBUILD_SHARED_LIBS=ON \
              -DBUILD_REGTEST=OFF \
              -DBUILD_TESTING=OFF \
              -DBUILD_EXAMPLES=OFF
      - cmd: |
          uv run --no-sync cmake --build CMakeBuild
      
  autoreconf:
    desc: Run autoreconf
    cmds:
      - cmd: |
          sh "{{toSlash .AUTOUPDATE}}" -fv
          sh "{{toSlash .AUTORECONF}}" -fvi

  deps:
    cmds:
      - cmd: |
          pacman -Syu
      - cmd: |
          pacman -S --needed --noconfirm \
            pkg-config autoconf2.72 automake1.17 libtool make \
            ${MINGW_PACKAGE_PREFIX}-gcc \
            ${MINGW_PACKAGE_PREFIX}-autotools \
            ${MINGW_PACKAGE_PREFIX}-libtool
